# configure timeseries type
timeseries_type: 'ASSOCIATED' #Retrieve only associated or disassociated series

# Configure S3 Bucket Names
s3_buckets:
  cold_tier_bucket_name: ''
  cold_tier_bucket_prefix: ''
  repartitioned_data_bucket_name: ''
  repartitioned_data_bucket_prefix: ''

# Configure temporary local directories for processing
local_dirs:
  local_tmp_raw_dir_name: 'raw'
  local_tmp_merged_dir_name: 'merged'

# Configure time range of SiteWise Cold Tier data to be processed
date_range:
  date_start: "2023-02-26"
  date_end: "2023-02-27"