# configure sitewise timeseries type
timeseries_type: 'ASSOCIATED' #Retrieve only associated or disassociated series

# Configure S3 Bucket Names
s3:
  cold_tier:
    bucket_name: 'coldtier2'
    data_prefix: 'raw/'
  repartitioned:
    bucket_name: 'sitewise-consolidated-tier-1'
    data_prefix: 'consolidated/'
    index_prefix: 'index/'
  glue_assets:
    bucket_name: 'sitewise-cold-tier-repartitioning-assets'
    scripts_prefix: 'scripts/'